version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ProjetWeb
            MYSQL_USER: ProjetWeb
            MYSQL_PASSWORD: scam.com
            MYSQL_ROOT_PASSWORD: a
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
        container_name: db
volumes:
    persistent:
