INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('Catsle-Nine', 'On peut appercevoir sur cette image un rare portrait d''Arthur Chateauneuf avec des oreilles de chat d''ou le titre de cette oeuvre "Catsle-Nine"', 'bleuchat.png',     5,   1, "person,bleu,cosplay,neutral expression,selfie");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('WOAF WOAF', 'Je vous presente mon animal de compagnie dans toute sa splandeur  ', 'chienluca.png',    2,   1, "dog");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('Kill comme Killian', 'Pour les fan de Jeu video je met en vente mon Killian, La photo a été prise par lui meme ce qui lui rajoute de la valeur. ', 'kil.png',    5,   1, "person,killian,selfie");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('50% DE LA L2 info', 'Cette image vaut son prix, c''est une moitié de photo de classe de la L2 info. On y retrouve touts les non habitués de la camera ', 'laclasse.png',     10,  1, "group,bleu,arthur,chad,luca,classe,nature");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('La montagne devant les pyrenne', 'On dit souvent que les montagnes ne se croisent jamais, voici la  preuve du contraire Avec Samy qui va a l''assaut des collines ', 'samymusl.png',     5,   1, "person,samy,flex,nature");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('2 sigma qui se fixent', 'La photo parle d''elle meme+Nocaption needed', 'shawncostume.png', 7,   1, "person,shawn,selfie,suit,serious");

INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('moments before disaster', 'Ceci est une photo prise durant lurbex effectuer dans la fac elle est plutot rare on peut y voir Arthur quelque seconde avant que le chantier tombe en ruines sur lui, mais heuresement qu il a fait crtl Z a temps pour eviter la mort', 'arthur_ruin.png', 6,   1, "nature,neutral expression,arthur,serious");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('zing & ming', 'La tete de classe en une seul photo incroyable non? ', 'exam.png', 8,   1, "shawn,neutral expression,chad,group,serious");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('English presentation', 'Encore une photo de groupe ou on peut voir killian et luca presenté un jeu video a la prof d''anglais en guise de PROJET FINAL ps:je trouve cela plus que studieux, moment incroyable dans l''histoire de l''UPVD!','Elden.png', 18,   1, "luca,killian,group,flex");
INSERT INTO stock (name, description, image, price, owner, tags) VALUES ('eliot', 'La raison pour laquelle tout les etudiants de cette classe on choisit la Licence info !', 'main_goal.png',5,   1, "flex,");